;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("org-capture-last-stored"
  (filename . "~/org/journal/2025-07-18.org")
  (front-context-string . "* arista.git -- ")
  (rear-context-string . "ckage{enumitem}\n")
  (position . 319)
  (last-modified 26746 14659 751404 0))
)
